const char = [
    '0',
    '1',
    '-',
    '_',
    '.',
    '2',
    '3',
    '-',
    '_',
    '.',
    '4',
    '5',
    '6',
    '7',
    '-',
    '_',
    '.',
    '8',
    '9',
    '-',
    '_',
    '.',
    'a',
    'b',
    'c',
    '-',
    '_',
    '.',
    'd',
    'e',
    'f',
    '-',
    '_',
    '.',
    'g',
    'h',
    'i',
    '-',
    '_',
    '.',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    '-',
    '_',
    '.',
    'q',
    'r',
    's',
    't',
    '-',
    '_',
    '.',
    'u',
    'v',
    '-',
    '_',
    '.',
    'w',
    'x',
    'y',
    'z'
]

const names = [
    'Emanuella Novaes',
    'Lavínia Farias',
    'Bernardo Ribeiro',
    'Luiz Miguel Rodrigues',
    'Helena Jesus',
    'Benício Campos',
    'Sarah Caldeira',
    'Kamilly Novaes',
    'Luiz Gustavo Sales',
    'Matheus Souza',
    'Bernardo Mendes',
    'Raquel Silva',
    'Joana Silveira',
    'Enzo Nogueira',
    'Isabelly da Cruz',
    'Isis Novaes',
    'Stella Moreira',
    'Luigi da Conceição',
    'Alexia Nascimento',
    'Leandro Peixoto',
    'Luiz Gustavo das Neves',
    'Larissa Costa',
    'Maria Cecília Duarte',
    'Carlos Eduardo da Cruz',
    'Melissa Viana',
    'Maria Luiza Jesus',
    'Marcos Vinicius da Mata',
    'José Tashiro de Oliveira',
    'Júlio Domen Sapateiro',
    'Leonardo Nomura Cavaco',
    'Leonardo Sazama Ferreira',
    'Leonardo Tanigawa de Nogueira',
    'Marina da Mata',
    'Manuela Farias',
    'Ana Luiza Rodrigues',
    'Maria Clara Freitas',
    'Vinicius Moreira',
    'Ana Vitória Araújo',
    'Vitor Nogueira',
    'Maria Luiza das Neves',
    'Luiz Fernando Rezende',
    'Davi Lucca Gonçalves',
    'Kevin Vieira',
    'Nicolas Moura',
    'Diogo Fogaça',
    'Luiz Felipe da Paz',
    'Francisco Nunes',
    'Davi Lucca Jesus',
    'Igor Cardoso',
    'Catarina Gomes',
    'Pedro Fogaça',
    'Bruna Porto',
    'Mirella Jesus',
    'João Lucas Costa',
    'Kaique Mendes',
    'Emanuel Araújo',
    'Vicente Rezende',
    'Maitê Costa',
    'Eloah Santos',
    'Hugo Watanabe Vasconcelos',
    'Jaime Noguchi Muto Meirelles Mascarenhas',
    'Jorge Takaki Bettencourt Do Rosário',
    'José Morishita Nunes',
    'José Soda Gusmão',
    'Carlos Eduardo da Cunha',
    'Ana Luiza Sales',
    'Miguel Peixoto',
    'Mirella Dias',
    'Gustavo Henrique Azevedo',
    'Esther Pires',
    'Antônio Barros',
    'Mariana Novaes',
    'Miguel Porto'
]

const domain = [
    '@gmail.com',
    '@hotmail.com',
    '@outlook.com',
    '@uol.com',
    '@gmail.com',
    '@hotmail.com',
    '@outlook.com',
    '@uol.com',
    '@gmail.com',
    '@hotmail.com',
    '@outlook.com',
    '@uol.com'
]

module.exports = {
    char: char,
    names: names,
    filter: letter => {
        letter = letter.replace(/[àáâã]/, 'a')
        letter = letter.replace(/[èéêẽ]/, 'e')
        letter = letter.replace(/[ìíîĩ]/, 'i')
        letter = letter.replace(/[òóôõ]/, 'o')
        letter = letter.replace(/[ùúûũ]/, 'u')
        letter = letter.replace(/[ç]/, 'c')

        return letter
    },
    domain: domain,
    mostrarNames: function () {
        for (const name of this.names) console.log(name)
    },
    reduceName: function (name) {
        var count = name.match(/ /g).length //4

        while (count > 2) {
            name = name.split(' ')
            name.pop()
            count--
            name = name.join(' ')
        }
        return name
    }
}
